apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- dploy.yaml
images:
- name: ackrzysztof/vote
  newTag: main-a6d776ca-1669543007 #{"$imagepolicy": "flux-system:vote:tag"}
configMapGenerator:
- name: extra-options
  envs:
  - options.env
