apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- dploy.yaml
images:
- name: schoolofdevops/vote
  newTag: v66
configMapGenerator:
- name: extra-options
  envs:
  - options.env
